package com.luckylas.crm.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ContactExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contact
     *
     * @mbg.generated Fri Oct 04 17:23:44 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contact
     *
     * @mbg.generated Fri Oct 04 17:23:44 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contact
     *
     * @mbg.generated Fri Oct 04 17:23:44 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Fri Oct 04 17:23:44 CST 2019
     */
    public ContactExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Fri Oct 04 17:23:44 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Fri Oct 04 17:23:44 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Fri Oct 04 17:23:44 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Fri Oct 04 17:23:44 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Fri Oct 04 17:23:44 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Fri Oct 04 17:23:44 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Fri Oct 04 17:23:44 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Fri Oct 04 17:23:44 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Fri Oct 04 17:23:44 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated Fri Oct 04 17:23:44 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table contact
     *
     * @mbg.generated Fri Oct 04 17:23:44 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andConIdIsNull() {
            addCriterion("con_id is null");
            return (Criteria) this;
        }

        public Criteria andConIdIsNotNull() {
            addCriterion("con_id is not null");
            return (Criteria) this;
        }

        public Criteria andConIdEqualTo(Integer value) {
            addCriterion("con_id =", value, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdNotEqualTo(Integer value) {
            addCriterion("con_id <>", value, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdGreaterThan(Integer value) {
            addCriterion("con_id >", value, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("con_id >=", value, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdLessThan(Integer value) {
            addCriterion("con_id <", value, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdLessThanOrEqualTo(Integer value) {
            addCriterion("con_id <=", value, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdIn(List<Integer> values) {
            addCriterion("con_id in", values, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdNotIn(List<Integer> values) {
            addCriterion("con_id not in", values, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdBetween(Integer value1, Integer value2) {
            addCriterion("con_id between", value1, value2, "conId");
            return (Criteria) this;
        }

        public Criteria andConIdNotBetween(Integer value1, Integer value2) {
            addCriterion("con_id not between", value1, value2, "conId");
            return (Criteria) this;
        }

        public Criteria andConNameIsNull() {
            addCriterion("con_name is null");
            return (Criteria) this;
        }

        public Criteria andConNameIsNotNull() {
            addCriterion("con_name is not null");
            return (Criteria) this;
        }

        public Criteria andConNameEqualTo(String value) {
            addCriterion("con_name =", value, "conName");
            return (Criteria) this;
        }

        public Criteria andConNameNotEqualTo(String value) {
            addCriterion("con_name <>", value, "conName");
            return (Criteria) this;
        }

        public Criteria andConNameGreaterThan(String value) {
            addCriterion("con_name >", value, "conName");
            return (Criteria) this;
        }

        public Criteria andConNameGreaterThanOrEqualTo(String value) {
            addCriterion("con_name >=", value, "conName");
            return (Criteria) this;
        }

        public Criteria andConNameLessThan(String value) {
            addCriterion("con_name <", value, "conName");
            return (Criteria) this;
        }

        public Criteria andConNameLessThanOrEqualTo(String value) {
            addCriterion("con_name <=", value, "conName");
            return (Criteria) this;
        }

        public Criteria andConNameLike(String value) {
            addCriterion("con_name like", value, "conName");
            return (Criteria) this;
        }

        public Criteria andConNameNotLike(String value) {
            addCriterion("con_name not like", value, "conName");
            return (Criteria) this;
        }

        public Criteria andConNameIn(List<String> values) {
            addCriterion("con_name in", values, "conName");
            return (Criteria) this;
        }

        public Criteria andConNameNotIn(List<String> values) {
            addCriterion("con_name not in", values, "conName");
            return (Criteria) this;
        }

        public Criteria andConNameBetween(String value1, String value2) {
            addCriterion("con_name between", value1, value2, "conName");
            return (Criteria) this;
        }

        public Criteria andConNameNotBetween(String value1, String value2) {
            addCriterion("con_name not between", value1, value2, "conName");
            return (Criteria) this;
        }

        public Criteria andConPhoneIsNull() {
            addCriterion("con_phone is null");
            return (Criteria) this;
        }

        public Criteria andConPhoneIsNotNull() {
            addCriterion("con_phone is not null");
            return (Criteria) this;
        }

        public Criteria andConPhoneEqualTo(String value) {
            addCriterion("con_phone =", value, "conPhone");
            return (Criteria) this;
        }

        public Criteria andConPhoneNotEqualTo(String value) {
            addCriterion("con_phone <>", value, "conPhone");
            return (Criteria) this;
        }

        public Criteria andConPhoneGreaterThan(String value) {
            addCriterion("con_phone >", value, "conPhone");
            return (Criteria) this;
        }

        public Criteria andConPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("con_phone >=", value, "conPhone");
            return (Criteria) this;
        }

        public Criteria andConPhoneLessThan(String value) {
            addCriterion("con_phone <", value, "conPhone");
            return (Criteria) this;
        }

        public Criteria andConPhoneLessThanOrEqualTo(String value) {
            addCriterion("con_phone <=", value, "conPhone");
            return (Criteria) this;
        }

        public Criteria andConPhoneLike(String value) {
            addCriterion("con_phone like", value, "conPhone");
            return (Criteria) this;
        }

        public Criteria andConPhoneNotLike(String value) {
            addCriterion("con_phone not like", value, "conPhone");
            return (Criteria) this;
        }

        public Criteria andConPhoneIn(List<String> values) {
            addCriterion("con_phone in", values, "conPhone");
            return (Criteria) this;
        }

        public Criteria andConPhoneNotIn(List<String> values) {
            addCriterion("con_phone not in", values, "conPhone");
            return (Criteria) this;
        }

        public Criteria andConPhoneBetween(String value1, String value2) {
            addCriterion("con_phone between", value1, value2, "conPhone");
            return (Criteria) this;
        }

        public Criteria andConPhoneNotBetween(String value1, String value2) {
            addCriterion("con_phone not between", value1, value2, "conPhone");
            return (Criteria) this;
        }

        public Criteria andConJobIsNull() {
            addCriterion("con_job is null");
            return (Criteria) this;
        }

        public Criteria andConJobIsNotNull() {
            addCriterion("con_job is not null");
            return (Criteria) this;
        }

        public Criteria andConJobEqualTo(String value) {
            addCriterion("con_job =", value, "conJob");
            return (Criteria) this;
        }

        public Criteria andConJobNotEqualTo(String value) {
            addCriterion("con_job <>", value, "conJob");
            return (Criteria) this;
        }

        public Criteria andConJobGreaterThan(String value) {
            addCriterion("con_job >", value, "conJob");
            return (Criteria) this;
        }

        public Criteria andConJobGreaterThanOrEqualTo(String value) {
            addCriterion("con_job >=", value, "conJob");
            return (Criteria) this;
        }

        public Criteria andConJobLessThan(String value) {
            addCriterion("con_job <", value, "conJob");
            return (Criteria) this;
        }

        public Criteria andConJobLessThanOrEqualTo(String value) {
            addCriterion("con_job <=", value, "conJob");
            return (Criteria) this;
        }

        public Criteria andConJobLike(String value) {
            addCriterion("con_job like", value, "conJob");
            return (Criteria) this;
        }

        public Criteria andConJobNotLike(String value) {
            addCriterion("con_job not like", value, "conJob");
            return (Criteria) this;
        }

        public Criteria andConJobIn(List<String> values) {
            addCriterion("con_job in", values, "conJob");
            return (Criteria) this;
        }

        public Criteria andConJobNotIn(List<String> values) {
            addCriterion("con_job not in", values, "conJob");
            return (Criteria) this;
        }

        public Criteria andConJobBetween(String value1, String value2) {
            addCriterion("con_job between", value1, value2, "conJob");
            return (Criteria) this;
        }

        public Criteria andConJobNotBetween(String value1, String value2) {
            addCriterion("con_job not between", value1, value2, "conJob");
            return (Criteria) this;
        }

        public Criteria andConDescIsNull() {
            addCriterion("con_desc is null");
            return (Criteria) this;
        }

        public Criteria andConDescIsNotNull() {
            addCriterion("con_desc is not null");
            return (Criteria) this;
        }

        public Criteria andConDescEqualTo(String value) {
            addCriterion("con_desc =", value, "conDesc");
            return (Criteria) this;
        }

        public Criteria andConDescNotEqualTo(String value) {
            addCriterion("con_desc <>", value, "conDesc");
            return (Criteria) this;
        }

        public Criteria andConDescGreaterThan(String value) {
            addCriterion("con_desc >", value, "conDesc");
            return (Criteria) this;
        }

        public Criteria andConDescGreaterThanOrEqualTo(String value) {
            addCriterion("con_desc >=", value, "conDesc");
            return (Criteria) this;
        }

        public Criteria andConDescLessThan(String value) {
            addCriterion("con_desc <", value, "conDesc");
            return (Criteria) this;
        }

        public Criteria andConDescLessThanOrEqualTo(String value) {
            addCriterion("con_desc <=", value, "conDesc");
            return (Criteria) this;
        }

        public Criteria andConDescLike(String value) {
            addCriterion("con_desc like", value, "conDesc");
            return (Criteria) this;
        }

        public Criteria andConDescNotLike(String value) {
            addCriterion("con_desc not like", value, "conDesc");
            return (Criteria) this;
        }

        public Criteria andConDescIn(List<String> values) {
            addCriterion("con_desc in", values, "conDesc");
            return (Criteria) this;
        }

        public Criteria andConDescNotIn(List<String> values) {
            addCriterion("con_desc not in", values, "conDesc");
            return (Criteria) this;
        }

        public Criteria andConDescBetween(String value1, String value2) {
            addCriterion("con_desc between", value1, value2, "conDesc");
            return (Criteria) this;
        }

        public Criteria andConDescNotBetween(String value1, String value2) {
            addCriterion("con_desc not between", value1, value2, "conDesc");
            return (Criteria) this;
        }

        public Criteria andConCreatetimeIsNull() {
            addCriterion("con_createTime is null");
            return (Criteria) this;
        }

        public Criteria andConCreatetimeIsNotNull() {
            addCriterion("con_createTime is not null");
            return (Criteria) this;
        }

        public Criteria andConCreatetimeEqualTo(Date value) {
            addCriterion("con_createTime =", value, "conCreatetime");
            return (Criteria) this;
        }

        public Criteria andConCreatetimeNotEqualTo(Date value) {
            addCriterion("con_createTime <>", value, "conCreatetime");
            return (Criteria) this;
        }

        public Criteria andConCreatetimeGreaterThan(Date value) {
            addCriterion("con_createTime >", value, "conCreatetime");
            return (Criteria) this;
        }

        public Criteria andConCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("con_createTime >=", value, "conCreatetime");
            return (Criteria) this;
        }

        public Criteria andConCreatetimeLessThan(Date value) {
            addCriterion("con_createTime <", value, "conCreatetime");
            return (Criteria) this;
        }

        public Criteria andConCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("con_createTime <=", value, "conCreatetime");
            return (Criteria) this;
        }

        public Criteria andConCreatetimeIn(List<Date> values) {
            addCriterion("con_createTime in", values, "conCreatetime");
            return (Criteria) this;
        }

        public Criteria andConCreatetimeNotIn(List<Date> values) {
            addCriterion("con_createTime not in", values, "conCreatetime");
            return (Criteria) this;
        }

        public Criteria andConCreatetimeBetween(Date value1, Date value2) {
            addCriterion("con_createTime between", value1, value2, "conCreatetime");
            return (Criteria) this;
        }

        public Criteria andConCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("con_createTime not between", value1, value2, "conCreatetime");
            return (Criteria) this;
        }

        public Criteria andCusIdIsNull() {
            addCriterion("cus_id is null");
            return (Criteria) this;
        }

        public Criteria andCusIdIsNotNull() {
            addCriterion("cus_id is not null");
            return (Criteria) this;
        }

        public Criteria andCusIdEqualTo(Integer value) {
            addCriterion("cus_id =", value, "cusId");
            return (Criteria) this;
        }

        public Criteria andCusIdNotEqualTo(Integer value) {
            addCriterion("cus_id <>", value, "cusId");
            return (Criteria) this;
        }

        public Criteria andCusIdGreaterThan(Integer value) {
            addCriterion("cus_id >", value, "cusId");
            return (Criteria) this;
        }

        public Criteria andCusIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cus_id >=", value, "cusId");
            return (Criteria) this;
        }

        public Criteria andCusIdLessThan(Integer value) {
            addCriterion("cus_id <", value, "cusId");
            return (Criteria) this;
        }

        public Criteria andCusIdLessThanOrEqualTo(Integer value) {
            addCriterion("cus_id <=", value, "cusId");
            return (Criteria) this;
        }

        public Criteria andCusIdIn(List<Integer> values) {
            addCriterion("cus_id in", values, "cusId");
            return (Criteria) this;
        }

        public Criteria andCusIdNotIn(List<Integer> values) {
            addCriterion("cus_id not in", values, "cusId");
            return (Criteria) this;
        }

        public Criteria andCusIdBetween(Integer value1, Integer value2) {
            addCriterion("cus_id between", value1, value2, "cusId");
            return (Criteria) this;
        }

        public Criteria andCusIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cus_id not between", value1, value2, "cusId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table contact
     *
     * @mbg.generated do_not_delete_during_merge Fri Oct 04 17:23:44 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table contact
     *
     * @mbg.generated Fri Oct 04 17:23:44 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}