package com.luckylas.crm.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CustomerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    public CustomerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCusIdIsNull() {
            addCriterion("cus_id is null");
            return (Criteria) this;
        }

        public Criteria andCusIdIsNotNull() {
            addCriterion("cus_id is not null");
            return (Criteria) this;
        }

        public Criteria andCusIdEqualTo(Integer value) {
            addCriterion("cus_id =", value, "cusId");
            return (Criteria) this;
        }

        public Criteria andCusIdNotEqualTo(Integer value) {
            addCriterion("cus_id <>", value, "cusId");
            return (Criteria) this;
        }

        public Criteria andCusIdGreaterThan(Integer value) {
            addCriterion("cus_id >", value, "cusId");
            return (Criteria) this;
        }

        public Criteria andCusIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cus_id >=", value, "cusId");
            return (Criteria) this;
        }

        public Criteria andCusIdLessThan(Integer value) {
            addCriterion("cus_id <", value, "cusId");
            return (Criteria) this;
        }

        public Criteria andCusIdLessThanOrEqualTo(Integer value) {
            addCriterion("cus_id <=", value, "cusId");
            return (Criteria) this;
        }

        public Criteria andCusIdIn(List<Integer> values) {
            addCriterion("cus_id in", values, "cusId");
            return (Criteria) this;
        }

        public Criteria andCusIdNotIn(List<Integer> values) {
            addCriterion("cus_id not in", values, "cusId");
            return (Criteria) this;
        }

        public Criteria andCusIdBetween(Integer value1, Integer value2) {
            addCriterion("cus_id between", value1, value2, "cusId");
            return (Criteria) this;
        }

        public Criteria andCusIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cus_id not between", value1, value2, "cusId");
            return (Criteria) this;
        }

        public Criteria andCusNameIsNull() {
            addCriterion("cus_name is null");
            return (Criteria) this;
        }

        public Criteria andCusNameIsNotNull() {
            addCriterion("cus_name is not null");
            return (Criteria) this;
        }

        public Criteria andCusNameEqualTo(String value) {
            addCriterion("cus_name =", value, "cusName");
            return (Criteria) this;
        }

        public Criteria andCusNameNotEqualTo(String value) {
            addCriterion("cus_name <>", value, "cusName");
            return (Criteria) this;
        }

        public Criteria andCusNameGreaterThan(String value) {
            addCriterion("cus_name >", value, "cusName");
            return (Criteria) this;
        }

        public Criteria andCusNameGreaterThanOrEqualTo(String value) {
            addCriterion("cus_name >=", value, "cusName");
            return (Criteria) this;
        }

        public Criteria andCusNameLessThan(String value) {
            addCriterion("cus_name <", value, "cusName");
            return (Criteria) this;
        }

        public Criteria andCusNameLessThanOrEqualTo(String value) {
            addCriterion("cus_name <=", value, "cusName");
            return (Criteria) this;
        }

        public Criteria andCusNameLike(String value) {
            addCriterion("cus_name like", value, "cusName");
            return (Criteria) this;
        }

        public Criteria andCusNameNotLike(String value) {
            addCriterion("cus_name not like", value, "cusName");
            return (Criteria) this;
        }

        public Criteria andCusNameIn(List<String> values) {
            addCriterion("cus_name in", values, "cusName");
            return (Criteria) this;
        }

        public Criteria andCusNameNotIn(List<String> values) {
            addCriterion("cus_name not in", values, "cusName");
            return (Criteria) this;
        }

        public Criteria andCusNameBetween(String value1, String value2) {
            addCriterion("cus_name between", value1, value2, "cusName");
            return (Criteria) this;
        }

        public Criteria andCusNameNotBetween(String value1, String value2) {
            addCriterion("cus_name not between", value1, value2, "cusName");
            return (Criteria) this;
        }

        public Criteria andCusZoneIsNull() {
            addCriterion("cus_zone is null");
            return (Criteria) this;
        }

        public Criteria andCusZoneIsNotNull() {
            addCriterion("cus_zone is not null");
            return (Criteria) this;
        }

        public Criteria andCusZoneEqualTo(String value) {
            addCriterion("cus_zone =", value, "cusZone");
            return (Criteria) this;
        }

        public Criteria andCusZoneNotEqualTo(String value) {
            addCriterion("cus_zone <>", value, "cusZone");
            return (Criteria) this;
        }

        public Criteria andCusZoneGreaterThan(String value) {
            addCriterion("cus_zone >", value, "cusZone");
            return (Criteria) this;
        }

        public Criteria andCusZoneGreaterThanOrEqualTo(String value) {
            addCriterion("cus_zone >=", value, "cusZone");
            return (Criteria) this;
        }

        public Criteria andCusZoneLessThan(String value) {
            addCriterion("cus_zone <", value, "cusZone");
            return (Criteria) this;
        }

        public Criteria andCusZoneLessThanOrEqualTo(String value) {
            addCriterion("cus_zone <=", value, "cusZone");
            return (Criteria) this;
        }

        public Criteria andCusZoneLike(String value) {
            addCriterion("cus_zone like", value, "cusZone");
            return (Criteria) this;
        }

        public Criteria andCusZoneNotLike(String value) {
            addCriterion("cus_zone not like", value, "cusZone");
            return (Criteria) this;
        }

        public Criteria andCusZoneIn(List<String> values) {
            addCriterion("cus_zone in", values, "cusZone");
            return (Criteria) this;
        }

        public Criteria andCusZoneNotIn(List<String> values) {
            addCriterion("cus_zone not in", values, "cusZone");
            return (Criteria) this;
        }

        public Criteria andCusZoneBetween(String value1, String value2) {
            addCriterion("cus_zone between", value1, value2, "cusZone");
            return (Criteria) this;
        }

        public Criteria andCusZoneNotBetween(String value1, String value2) {
            addCriterion("cus_zone not between", value1, value2, "cusZone");
            return (Criteria) this;
        }

        public Criteria andCusAddressIsNull() {
            addCriterion("cus_address is null");
            return (Criteria) this;
        }

        public Criteria andCusAddressIsNotNull() {
            addCriterion("cus_address is not null");
            return (Criteria) this;
        }

        public Criteria andCusAddressEqualTo(String value) {
            addCriterion("cus_address =", value, "cusAddress");
            return (Criteria) this;
        }

        public Criteria andCusAddressNotEqualTo(String value) {
            addCriterion("cus_address <>", value, "cusAddress");
            return (Criteria) this;
        }

        public Criteria andCusAddressGreaterThan(String value) {
            addCriterion("cus_address >", value, "cusAddress");
            return (Criteria) this;
        }

        public Criteria andCusAddressGreaterThanOrEqualTo(String value) {
            addCriterion("cus_address >=", value, "cusAddress");
            return (Criteria) this;
        }

        public Criteria andCusAddressLessThan(String value) {
            addCriterion("cus_address <", value, "cusAddress");
            return (Criteria) this;
        }

        public Criteria andCusAddressLessThanOrEqualTo(String value) {
            addCriterion("cus_address <=", value, "cusAddress");
            return (Criteria) this;
        }

        public Criteria andCusAddressLike(String value) {
            addCriterion("cus_address like", value, "cusAddress");
            return (Criteria) this;
        }

        public Criteria andCusAddressNotLike(String value) {
            addCriterion("cus_address not like", value, "cusAddress");
            return (Criteria) this;
        }

        public Criteria andCusAddressIn(List<String> values) {
            addCriterion("cus_address in", values, "cusAddress");
            return (Criteria) this;
        }

        public Criteria andCusAddressNotIn(List<String> values) {
            addCriterion("cus_address not in", values, "cusAddress");
            return (Criteria) this;
        }

        public Criteria andCusAddressBetween(String value1, String value2) {
            addCriterion("cus_address between", value1, value2, "cusAddress");
            return (Criteria) this;
        }

        public Criteria andCusAddressNotBetween(String value1, String value2) {
            addCriterion("cus_address not between", value1, value2, "cusAddress");
            return (Criteria) this;
        }

        public Criteria andCusWebsiteIsNull() {
            addCriterion("cus_website is null");
            return (Criteria) this;
        }

        public Criteria andCusWebsiteIsNotNull() {
            addCriterion("cus_website is not null");
            return (Criteria) this;
        }

        public Criteria andCusWebsiteEqualTo(String value) {
            addCriterion("cus_website =", value, "cusWebsite");
            return (Criteria) this;
        }

        public Criteria andCusWebsiteNotEqualTo(String value) {
            addCriterion("cus_website <>", value, "cusWebsite");
            return (Criteria) this;
        }

        public Criteria andCusWebsiteGreaterThan(String value) {
            addCriterion("cus_website >", value, "cusWebsite");
            return (Criteria) this;
        }

        public Criteria andCusWebsiteGreaterThanOrEqualTo(String value) {
            addCriterion("cus_website >=", value, "cusWebsite");
            return (Criteria) this;
        }

        public Criteria andCusWebsiteLessThan(String value) {
            addCriterion("cus_website <", value, "cusWebsite");
            return (Criteria) this;
        }

        public Criteria andCusWebsiteLessThanOrEqualTo(String value) {
            addCriterion("cus_website <=", value, "cusWebsite");
            return (Criteria) this;
        }

        public Criteria andCusWebsiteLike(String value) {
            addCriterion("cus_website like", value, "cusWebsite");
            return (Criteria) this;
        }

        public Criteria andCusWebsiteNotLike(String value) {
            addCriterion("cus_website not like", value, "cusWebsite");
            return (Criteria) this;
        }

        public Criteria andCusWebsiteIn(List<String> values) {
            addCriterion("cus_website in", values, "cusWebsite");
            return (Criteria) this;
        }

        public Criteria andCusWebsiteNotIn(List<String> values) {
            addCriterion("cus_website not in", values, "cusWebsite");
            return (Criteria) this;
        }

        public Criteria andCusWebsiteBetween(String value1, String value2) {
            addCriterion("cus_website between", value1, value2, "cusWebsite");
            return (Criteria) this;
        }

        public Criteria andCusWebsiteNotBetween(String value1, String value2) {
            addCriterion("cus_website not between", value1, value2, "cusWebsite");
            return (Criteria) this;
        }

        public Criteria andCusLevelIsNull() {
            addCriterion("cus_level is null");
            return (Criteria) this;
        }

        public Criteria andCusLevelIsNotNull() {
            addCriterion("cus_level is not null");
            return (Criteria) this;
        }

        public Criteria andCusLevelEqualTo(String value) {
            addCriterion("cus_level =", value, "cusLevel");
            return (Criteria) this;
        }

        public Criteria andCusLevelNotEqualTo(String value) {
            addCriterion("cus_level <>", value, "cusLevel");
            return (Criteria) this;
        }

        public Criteria andCusLevelGreaterThan(String value) {
            addCriterion("cus_level >", value, "cusLevel");
            return (Criteria) this;
        }

        public Criteria andCusLevelGreaterThanOrEqualTo(String value) {
            addCriterion("cus_level >=", value, "cusLevel");
            return (Criteria) this;
        }

        public Criteria andCusLevelLessThan(String value) {
            addCriterion("cus_level <", value, "cusLevel");
            return (Criteria) this;
        }

        public Criteria andCusLevelLessThanOrEqualTo(String value) {
            addCriterion("cus_level <=", value, "cusLevel");
            return (Criteria) this;
        }

        public Criteria andCusLevelLike(String value) {
            addCriterion("cus_level like", value, "cusLevel");
            return (Criteria) this;
        }

        public Criteria andCusLevelNotLike(String value) {
            addCriterion("cus_level not like", value, "cusLevel");
            return (Criteria) this;
        }

        public Criteria andCusLevelIn(List<String> values) {
            addCriterion("cus_level in", values, "cusLevel");
            return (Criteria) this;
        }

        public Criteria andCusLevelNotIn(List<String> values) {
            addCriterion("cus_level not in", values, "cusLevel");
            return (Criteria) this;
        }

        public Criteria andCusLevelBetween(String value1, String value2) {
            addCriterion("cus_level between", value1, value2, "cusLevel");
            return (Criteria) this;
        }

        public Criteria andCusLevelNotBetween(String value1, String value2) {
            addCriterion("cus_level not between", value1, value2, "cusLevel");
            return (Criteria) this;
        }

        public Criteria andCusStarIsNull() {
            addCriterion("cus_star is null");
            return (Criteria) this;
        }

        public Criteria andCusStarIsNotNull() {
            addCriterion("cus_star is not null");
            return (Criteria) this;
        }

        public Criteria andCusStarEqualTo(String value) {
            addCriterion("cus_star =", value, "cusStar");
            return (Criteria) this;
        }

        public Criteria andCusStarNotEqualTo(String value) {
            addCriterion("cus_star <>", value, "cusStar");
            return (Criteria) this;
        }

        public Criteria andCusStarGreaterThan(String value) {
            addCriterion("cus_star >", value, "cusStar");
            return (Criteria) this;
        }

        public Criteria andCusStarGreaterThanOrEqualTo(String value) {
            addCriterion("cus_star >=", value, "cusStar");
            return (Criteria) this;
        }

        public Criteria andCusStarLessThan(String value) {
            addCriterion("cus_star <", value, "cusStar");
            return (Criteria) this;
        }

        public Criteria andCusStarLessThanOrEqualTo(String value) {
            addCriterion("cus_star <=", value, "cusStar");
            return (Criteria) this;
        }

        public Criteria andCusStarLike(String value) {
            addCriterion("cus_star like", value, "cusStar");
            return (Criteria) this;
        }

        public Criteria andCusStarNotLike(String value) {
            addCriterion("cus_star not like", value, "cusStar");
            return (Criteria) this;
        }

        public Criteria andCusStarIn(List<String> values) {
            addCriterion("cus_star in", values, "cusStar");
            return (Criteria) this;
        }

        public Criteria andCusStarNotIn(List<String> values) {
            addCriterion("cus_star not in", values, "cusStar");
            return (Criteria) this;
        }

        public Criteria andCusStarBetween(String value1, String value2) {
            addCriterion("cus_star between", value1, value2, "cusStar");
            return (Criteria) this;
        }

        public Criteria andCusStarNotBetween(String value1, String value2) {
            addCriterion("cus_star not between", value1, value2, "cusStar");
            return (Criteria) this;
        }

        public Criteria andCusCreatetimeIsNull() {
            addCriterion("cus_createTime is null");
            return (Criteria) this;
        }

        public Criteria andCusCreatetimeIsNotNull() {
            addCriterion("cus_createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCusCreatetimeEqualTo(Date value) {
            addCriterion("cus_createTime =", value, "cusCreatetime");
            return (Criteria) this;
        }

        public Criteria andCusCreatetimeNotEqualTo(Date value) {
            addCriterion("cus_createTime <>", value, "cusCreatetime");
            return (Criteria) this;
        }

        public Criteria andCusCreatetimeGreaterThan(Date value) {
            addCriterion("cus_createTime >", value, "cusCreatetime");
            return (Criteria) this;
        }

        public Criteria andCusCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("cus_createTime >=", value, "cusCreatetime");
            return (Criteria) this;
        }

        public Criteria andCusCreatetimeLessThan(Date value) {
            addCriterion("cus_createTime <", value, "cusCreatetime");
            return (Criteria) this;
        }

        public Criteria andCusCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("cus_createTime <=", value, "cusCreatetime");
            return (Criteria) this;
        }

        public Criteria andCusCreatetimeIn(List<Date> values) {
            addCriterion("cus_createTime in", values, "cusCreatetime");
            return (Criteria) this;
        }

        public Criteria andCusCreatetimeNotIn(List<Date> values) {
            addCriterion("cus_createTime not in", values, "cusCreatetime");
            return (Criteria) this;
        }

        public Criteria andCusCreatetimeBetween(Date value1, Date value2) {
            addCriterion("cus_createTime between", value1, value2, "cusCreatetime");
            return (Criteria) this;
        }

        public Criteria andCusCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("cus_createTime not between", value1, value2, "cusCreatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer
     *
     * @mbg.generated do_not_delete_during_merge Fri Oct 04 17:23:51 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}