package com.luckylas.crm.entity;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * 客户实体类
 * @author luckyliuqs
 *
 */
public class Customer {
    /**
     * 客户id
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cus_id
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    private Integer cusId;

    /**
     * 客户名称
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cus_name
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    private String cusName;

    /**
     * 客户所属地区（华中，华北，华东，华南，华西）
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cus_zone
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    private String cusZone;

    /**
     * 客户地址
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cus_address
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    private String cusAddress;

    /**
     * 客户网站
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cus_website
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    private String cusWebsite;

    /**
     * 客户级别：普通客户，大客户，重点开发客户，VIP客户，合作伙伴，战略合作伙伴。
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cus_level
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    private String cusLevel;

    /**
     * 客户信誉等级（1-5）
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cus_star
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    private String cusStar;

    /**
     * 客户创建时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cus_createTime
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date cusCreatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cus_id
     *
     * @return the value of customer.cus_id
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    public Integer getCusId() {
        return cusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cus_id
     *
     * @param cusId the value for customer.cus_id
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    public void setCusId(Integer cusId) {
        this.cusId = cusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cus_name
     *
     * @return the value of customer.cus_name
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    public String getCusName() {
        return cusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cus_name
     *
     * @param cusName the value for customer.cus_name
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    public void setCusName(String cusName) {
        this.cusName = cusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cus_zone
     *
     * @return the value of customer.cus_zone
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    public String getCusZone() {
        return cusZone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cus_zone
     *
     * @param cusZone the value for customer.cus_zone
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    public void setCusZone(String cusZone) {
        this.cusZone = cusZone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cus_address
     *
     * @return the value of customer.cus_address
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    public String getCusAddress() {
        return cusAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cus_address
     *
     * @param cusAddress the value for customer.cus_address
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    public void setCusAddress(String cusAddress) {
        this.cusAddress = cusAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cus_website
     *
     * @return the value of customer.cus_website
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    public String getCusWebsite() {
        return cusWebsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cus_website
     *
     * @param cusWebsite the value for customer.cus_website
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    public void setCusWebsite(String cusWebsite) {
        this.cusWebsite = cusWebsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cus_level
     *
     * @return the value of customer.cus_level
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    public String getCusLevel() {
        return cusLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cus_level
     *
     * @param cusLevel the value for customer.cus_level
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    public void setCusLevel(String cusLevel) {
        this.cusLevel = cusLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cus_star
     *
     * @return the value of customer.cus_star
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    public String getCusStar() {
        return cusStar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cus_star
     *
     * @param cusStar the value for customer.cus_star
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    public void setCusStar(String cusStar) {
        this.cusStar = cusStar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cus_createTime
     *
     * @return the value of customer.cus_createTime
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    public Date getCusCreatetime() {
        return cusCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cus_createTime
     *
     * @param cusCreatetime the value for customer.cus_createTime
     *
     * @mbg.generated Fri Oct 04 17:23:51 CST 2019
     */
    public void setCusCreatetime(Date cusCreatetime) {
        this.cusCreatetime = cusCreatetime;
    }

	@Override
	public String toString() {
		return "Customer [cusId=" + cusId + ", cusName=" + cusName + ", cusZone=" + cusZone + ", cusAddress="
				+ cusAddress + ", cusWebsite=" + cusWebsite + ", cusLevel=" + cusLevel + ", cusStar=" + cusStar
				+ ", cusCreatetime=" + cusCreatetime + "]";
	}
    
}