package com.luckylas.crm.entity;

/**
 * 用户角色实体类
 * @author luckyliuqs
 *
 */
public class Role {
    /**
     * 角色id
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.r_id
     *
     * @mbg.generated Mon Sep 30 11:42:45 CST 2019
     */
    private Integer rId;

    /**
     * 角色名称：管理员，营销主管，销售经理
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.r_name
     *
     * @mbg.generated Mon Sep 30 11:42:45 CST 2019
     */
    private String rName;

    /**
     * 角色描述
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.r_desc
     *
     * @mbg.generated Mon Sep 30 11:42:45 CST 2019
     */
    private String rDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.r_id
     *
     * @return the value of role.r_id
     *
     * @mbg.generated Mon Sep 30 11:42:45 CST 2019
     */
    public Integer getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.r_id
     *
     * @param rId the value for role.r_id
     *
     * @mbg.generated Mon Sep 30 11:42:45 CST 2019
     */
    public void setrId(Integer rId) {
        this.rId = rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.r_name
     *
     * @return the value of role.r_name
     *
     * @mbg.generated Mon Sep 30 11:42:45 CST 2019
     */
    public String getrName() {
        return rName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.r_name
     *
     * @param rName the value for role.r_name
     *
     * @mbg.generated Mon Sep 30 11:42:45 CST 2019
     */
    public void setrName(String rName) {
        this.rName = rName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.r_desc
     *
     * @return the value of role.r_desc
     *
     * @mbg.generated Mon Sep 30 11:42:45 CST 2019
     */
    public String getrDesc() {
        return rDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.r_desc
     *
     * @param rDesc the value for role.r_desc
     *
     * @mbg.generated Mon Sep 30 11:42:45 CST 2019
     */
    public void setrDesc(String rDesc) {
        this.rDesc = rDesc;
    }
}