package com.luckylas.crm.entity;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * 销售计划实体类
 * @author luckyliuqs
 *
 */
public class SalePlan {
    /**
     * 销售计划id
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_plan.sp_id
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    private Integer spId;

    /**
     * 销售计划创建时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_plan.sp_createTime
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date spCreatetime;

    /** 
     * 销售计划执行时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_plan.sp_beginTime
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date spBegintime;

    /**
     * 销售计划内容
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_plan.sp_content
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    private String spContent;

    /**
     * 销售计划状态:0-正在开发中，1-开发失败，2-开发成功
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_plan.sp_status
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    private Integer spStatus;

    /**
     * 销售机会id
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_plan.sp_scId
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    private Integer spScid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_plan.sp_id
     *
     * @return the value of sale_plan.sp_id
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    public Integer getSpId() {
        return spId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_plan.sp_id
     *
     * @param spId the value for sale_plan.sp_id
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    public void setSpId(Integer spId) {
        this.spId = spId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_plan.sp_createTime
     *
     * @return the value of sale_plan.sp_createTime
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    public Date getSpCreatetime() {
        return spCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_plan.sp_createTime
     *
     * @param spCreatetime the value for sale_plan.sp_createTime
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    public void setSpCreatetime(Date spCreatetime) {
        this.spCreatetime = spCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_plan.sp_beginTime
     *
     * @return the value of sale_plan.sp_beginTime
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    public Date getSpBegintime() {
        return spBegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_plan.sp_beginTime
     *
     * @param spBegintime the value for sale_plan.sp_beginTime
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    public void setSpBegintime(Date spBegintime) {
        this.spBegintime = spBegintime;
    }
    
    public void setSpBegintime(String timeStr) {
    	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        try {
			this.spBegintime = sdf.parse(timeStr);
		} catch (ParseException e) {
			e.printStackTrace();
		}
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_plan.sp_content
     *
     * @return the value of sale_plan.sp_content
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    public String getSpContent() {
        return spContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_plan.sp_content
     *
     * @param spContent the value for sale_plan.sp_content
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    public void setSpContent(String spContent) {
        this.spContent = spContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_plan.sp_status
     *
     * @return the value of sale_plan.sp_status
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    public Integer getSpStatus() {
        return spStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_plan.sp_status
     *
     * @param spStatus the value for sale_plan.sp_status
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    public void setSpStatus(Integer spStatus) {
        this.spStatus = spStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_plan.sp_scId
     *
     * @return the value of sale_plan.sp_scId
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    public Integer getSpScid() {
        return spScid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_plan.sp_scId
     *
     * @param spScid the value for sale_plan.sp_scId
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    public void setSpScid(Integer spScid) {
        this.spScid = spScid;
    }
}