package com.luckylas.crm.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SalePlanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sale_plan
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sale_plan
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sale_plan
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    public SalePlanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sale_plan
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSpIdIsNull() {
            addCriterion("sp_id is null");
            return (Criteria) this;
        }

        public Criteria andSpIdIsNotNull() {
            addCriterion("sp_id is not null");
            return (Criteria) this;
        }

        public Criteria andSpIdEqualTo(Integer value) {
            addCriterion("sp_id =", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdNotEqualTo(Integer value) {
            addCriterion("sp_id <>", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdGreaterThan(Integer value) {
            addCriterion("sp_id >", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sp_id >=", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdLessThan(Integer value) {
            addCriterion("sp_id <", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdLessThanOrEqualTo(Integer value) {
            addCriterion("sp_id <=", value, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdIn(List<Integer> values) {
            addCriterion("sp_id in", values, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdNotIn(List<Integer> values) {
            addCriterion("sp_id not in", values, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdBetween(Integer value1, Integer value2) {
            addCriterion("sp_id between", value1, value2, "spId");
            return (Criteria) this;
        }

        public Criteria andSpIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sp_id not between", value1, value2, "spId");
            return (Criteria) this;
        }

        public Criteria andSpCreatetimeIsNull() {
            addCriterion("sp_createTime is null");
            return (Criteria) this;
        }

        public Criteria andSpCreatetimeIsNotNull() {
            addCriterion("sp_createTime is not null");
            return (Criteria) this;
        }

        public Criteria andSpCreatetimeEqualTo(Date value) {
            addCriterion("sp_createTime =", value, "spCreatetime");
            return (Criteria) this;
        }

        public Criteria andSpCreatetimeNotEqualTo(Date value) {
            addCriterion("sp_createTime <>", value, "spCreatetime");
            return (Criteria) this;
        }

        public Criteria andSpCreatetimeGreaterThan(Date value) {
            addCriterion("sp_createTime >", value, "spCreatetime");
            return (Criteria) this;
        }

        public Criteria andSpCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sp_createTime >=", value, "spCreatetime");
            return (Criteria) this;
        }

        public Criteria andSpCreatetimeLessThan(Date value) {
            addCriterion("sp_createTime <", value, "spCreatetime");
            return (Criteria) this;
        }

        public Criteria andSpCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("sp_createTime <=", value, "spCreatetime");
            return (Criteria) this;
        }

        public Criteria andSpCreatetimeIn(List<Date> values) {
            addCriterion("sp_createTime in", values, "spCreatetime");
            return (Criteria) this;
        }

        public Criteria andSpCreatetimeNotIn(List<Date> values) {
            addCriterion("sp_createTime not in", values, "spCreatetime");
            return (Criteria) this;
        }

        public Criteria andSpCreatetimeBetween(Date value1, Date value2) {
            addCriterion("sp_createTime between", value1, value2, "spCreatetime");
            return (Criteria) this;
        }

        public Criteria andSpCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("sp_createTime not between", value1, value2, "spCreatetime");
            return (Criteria) this;
        }

        public Criteria andSpBegintimeIsNull() {
            addCriterion("sp_beginTime is null");
            return (Criteria) this;
        }

        public Criteria andSpBegintimeIsNotNull() {
            addCriterion("sp_beginTime is not null");
            return (Criteria) this;
        }

        public Criteria andSpBegintimeEqualTo(Date value) {
            addCriterion("sp_beginTime =", value, "spBegintime");
            return (Criteria) this;
        }

        public Criteria andSpBegintimeNotEqualTo(Date value) {
            addCriterion("sp_beginTime <>", value, "spBegintime");
            return (Criteria) this;
        }

        public Criteria andSpBegintimeGreaterThan(Date value) {
            addCriterion("sp_beginTime >", value, "spBegintime");
            return (Criteria) this;
        }

        public Criteria andSpBegintimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sp_beginTime >=", value, "spBegintime");
            return (Criteria) this;
        }

        public Criteria andSpBegintimeLessThan(Date value) {
            addCriterion("sp_beginTime <", value, "spBegintime");
            return (Criteria) this;
        }

        public Criteria andSpBegintimeLessThanOrEqualTo(Date value) {
            addCriterion("sp_beginTime <=", value, "spBegintime");
            return (Criteria) this;
        }

        public Criteria andSpBegintimeIn(List<Date> values) {
            addCriterion("sp_beginTime in", values, "spBegintime");
            return (Criteria) this;
        }

        public Criteria andSpBegintimeNotIn(List<Date> values) {
            addCriterion("sp_beginTime not in", values, "spBegintime");
            return (Criteria) this;
        }

        public Criteria andSpBegintimeBetween(Date value1, Date value2) {
            addCriterion("sp_beginTime between", value1, value2, "spBegintime");
            return (Criteria) this;
        }

        public Criteria andSpBegintimeNotBetween(Date value1, Date value2) {
            addCriterion("sp_beginTime not between", value1, value2, "spBegintime");
            return (Criteria) this;
        }

        public Criteria andSpContentIsNull() {
            addCriterion("sp_content is null");
            return (Criteria) this;
        }

        public Criteria andSpContentIsNotNull() {
            addCriterion("sp_content is not null");
            return (Criteria) this;
        }

        public Criteria andSpContentEqualTo(String value) {
            addCriterion("sp_content =", value, "spContent");
            return (Criteria) this;
        }

        public Criteria andSpContentNotEqualTo(String value) {
            addCriterion("sp_content <>", value, "spContent");
            return (Criteria) this;
        }

        public Criteria andSpContentGreaterThan(String value) {
            addCriterion("sp_content >", value, "spContent");
            return (Criteria) this;
        }

        public Criteria andSpContentGreaterThanOrEqualTo(String value) {
            addCriterion("sp_content >=", value, "spContent");
            return (Criteria) this;
        }

        public Criteria andSpContentLessThan(String value) {
            addCriterion("sp_content <", value, "spContent");
            return (Criteria) this;
        }

        public Criteria andSpContentLessThanOrEqualTo(String value) {
            addCriterion("sp_content <=", value, "spContent");
            return (Criteria) this;
        }

        public Criteria andSpContentLike(String value) {
            addCriterion("sp_content like", value, "spContent");
            return (Criteria) this;
        }

        public Criteria andSpContentNotLike(String value) {
            addCriterion("sp_content not like", value, "spContent");
            return (Criteria) this;
        }

        public Criteria andSpContentIn(List<String> values) {
            addCriterion("sp_content in", values, "spContent");
            return (Criteria) this;
        }

        public Criteria andSpContentNotIn(List<String> values) {
            addCriterion("sp_content not in", values, "spContent");
            return (Criteria) this;
        }

        public Criteria andSpContentBetween(String value1, String value2) {
            addCriterion("sp_content between", value1, value2, "spContent");
            return (Criteria) this;
        }

        public Criteria andSpContentNotBetween(String value1, String value2) {
            addCriterion("sp_content not between", value1, value2, "spContent");
            return (Criteria) this;
        }

        public Criteria andSpStatusIsNull() {
            addCriterion("sp_status is null");
            return (Criteria) this;
        }

        public Criteria andSpStatusIsNotNull() {
            addCriterion("sp_status is not null");
            return (Criteria) this;
        }

        public Criteria andSpStatusEqualTo(Integer value) {
            addCriterion("sp_status =", value, "spStatus");
            return (Criteria) this;
        }

        public Criteria andSpStatusNotEqualTo(Integer value) {
            addCriterion("sp_status <>", value, "spStatus");
            return (Criteria) this;
        }

        public Criteria andSpStatusGreaterThan(Integer value) {
            addCriterion("sp_status >", value, "spStatus");
            return (Criteria) this;
        }

        public Criteria andSpStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("sp_status >=", value, "spStatus");
            return (Criteria) this;
        }

        public Criteria andSpStatusLessThan(Integer value) {
            addCriterion("sp_status <", value, "spStatus");
            return (Criteria) this;
        }

        public Criteria andSpStatusLessThanOrEqualTo(Integer value) {
            addCriterion("sp_status <=", value, "spStatus");
            return (Criteria) this;
        }

        public Criteria andSpStatusIn(List<Integer> values) {
            addCriterion("sp_status in", values, "spStatus");
            return (Criteria) this;
        }

        public Criteria andSpStatusNotIn(List<Integer> values) {
            addCriterion("sp_status not in", values, "spStatus");
            return (Criteria) this;
        }

        public Criteria andSpStatusBetween(Integer value1, Integer value2) {
            addCriterion("sp_status between", value1, value2, "spStatus");
            return (Criteria) this;
        }

        public Criteria andSpStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("sp_status not between", value1, value2, "spStatus");
            return (Criteria) this;
        }

        public Criteria andSpScidIsNull() {
            addCriterion("sp_scId is null");
            return (Criteria) this;
        }

        public Criteria andSpScidIsNotNull() {
            addCriterion("sp_scId is not null");
            return (Criteria) this;
        }

        public Criteria andSpScidEqualTo(Integer value) {
            addCriterion("sp_scId =", value, "spScid");
            return (Criteria) this;
        }

        public Criteria andSpScidNotEqualTo(Integer value) {
            addCriterion("sp_scId <>", value, "spScid");
            return (Criteria) this;
        }

        public Criteria andSpScidGreaterThan(Integer value) {
            addCriterion("sp_scId >", value, "spScid");
            return (Criteria) this;
        }

        public Criteria andSpScidGreaterThanOrEqualTo(Integer value) {
            addCriterion("sp_scId >=", value, "spScid");
            return (Criteria) this;
        }

        public Criteria andSpScidLessThan(Integer value) {
            addCriterion("sp_scId <", value, "spScid");
            return (Criteria) this;
        }

        public Criteria andSpScidLessThanOrEqualTo(Integer value) {
            addCriterion("sp_scId <=", value, "spScid");
            return (Criteria) this;
        }

        public Criteria andSpScidIn(List<Integer> values) {
            addCriterion("sp_scId in", values, "spScid");
            return (Criteria) this;
        }

        public Criteria andSpScidNotIn(List<Integer> values) {
            addCriterion("sp_scId not in", values, "spScid");
            return (Criteria) this;
        }

        public Criteria andSpScidBetween(Integer value1, Integer value2) {
            addCriterion("sp_scId between", value1, value2, "spScid");
            return (Criteria) this;
        }

        public Criteria andSpScidNotBetween(Integer value1, Integer value2) {
            addCriterion("sp_scId not between", value1, value2, "spScid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sale_plan
     *
     * @mbg.generated do_not_delete_during_merge Mon Sep 30 11:43:08 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sale_plan
     *
     * @mbg.generated Mon Sep 30 11:43:08 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}