package com.luckylas.crm.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SalePlanExeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sale_plan_exe
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sale_plan_exe
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sale_plan_exe
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan_exe
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    public SalePlanExeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan_exe
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan_exe
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan_exe
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan_exe
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan_exe
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan_exe
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan_exe
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan_exe
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan_exe
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan_exe
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sale_plan_exe
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSpeIdIsNull() {
            addCriterion("spe_id is null");
            return (Criteria) this;
        }

        public Criteria andSpeIdIsNotNull() {
            addCriterion("spe_id is not null");
            return (Criteria) this;
        }

        public Criteria andSpeIdEqualTo(Integer value) {
            addCriterion("spe_id =", value, "speId");
            return (Criteria) this;
        }

        public Criteria andSpeIdNotEqualTo(Integer value) {
            addCriterion("spe_id <>", value, "speId");
            return (Criteria) this;
        }

        public Criteria andSpeIdGreaterThan(Integer value) {
            addCriterion("spe_id >", value, "speId");
            return (Criteria) this;
        }

        public Criteria andSpeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("spe_id >=", value, "speId");
            return (Criteria) this;
        }

        public Criteria andSpeIdLessThan(Integer value) {
            addCriterion("spe_id <", value, "speId");
            return (Criteria) this;
        }

        public Criteria andSpeIdLessThanOrEqualTo(Integer value) {
            addCriterion("spe_id <=", value, "speId");
            return (Criteria) this;
        }

        public Criteria andSpeIdIn(List<Integer> values) {
            addCriterion("spe_id in", values, "speId");
            return (Criteria) this;
        }

        public Criteria andSpeIdNotIn(List<Integer> values) {
            addCriterion("spe_id not in", values, "speId");
            return (Criteria) this;
        }

        public Criteria andSpeIdBetween(Integer value1, Integer value2) {
            addCriterion("spe_id between", value1, value2, "speId");
            return (Criteria) this;
        }

        public Criteria andSpeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("spe_id not between", value1, value2, "speId");
            return (Criteria) this;
        }

        public Criteria andSpeExecaseIsNull() {
            addCriterion("spe_exeCase is null");
            return (Criteria) this;
        }

        public Criteria andSpeExecaseIsNotNull() {
            addCriterion("spe_exeCase is not null");
            return (Criteria) this;
        }

        public Criteria andSpeExecaseEqualTo(String value) {
            addCriterion("spe_exeCase =", value, "speExecase");
            return (Criteria) this;
        }

        public Criteria andSpeExecaseNotEqualTo(String value) {
            addCriterion("spe_exeCase <>", value, "speExecase");
            return (Criteria) this;
        }

        public Criteria andSpeExecaseGreaterThan(String value) {
            addCriterion("spe_exeCase >", value, "speExecase");
            return (Criteria) this;
        }

        public Criteria andSpeExecaseGreaterThanOrEqualTo(String value) {
            addCriterion("spe_exeCase >=", value, "speExecase");
            return (Criteria) this;
        }

        public Criteria andSpeExecaseLessThan(String value) {
            addCriterion("spe_exeCase <", value, "speExecase");
            return (Criteria) this;
        }

        public Criteria andSpeExecaseLessThanOrEqualTo(String value) {
            addCriterion("spe_exeCase <=", value, "speExecase");
            return (Criteria) this;
        }

        public Criteria andSpeExecaseLike(String value) {
            addCriterion("spe_exeCase like", value, "speExecase");
            return (Criteria) this;
        }

        public Criteria andSpeExecaseNotLike(String value) {
            addCriterion("spe_exeCase not like", value, "speExecase");
            return (Criteria) this;
        }

        public Criteria andSpeExecaseIn(List<String> values) {
            addCriterion("spe_exeCase in", values, "speExecase");
            return (Criteria) this;
        }

        public Criteria andSpeExecaseNotIn(List<String> values) {
            addCriterion("spe_exeCase not in", values, "speExecase");
            return (Criteria) this;
        }

        public Criteria andSpeExecaseBetween(String value1, String value2) {
            addCriterion("spe_exeCase between", value1, value2, "speExecase");
            return (Criteria) this;
        }

        public Criteria andSpeExecaseNotBetween(String value1, String value2) {
            addCriterion("spe_exeCase not between", value1, value2, "speExecase");
            return (Criteria) this;
        }

        public Criteria andSpeExetimeIsNull() {
            addCriterion("spe_exeTime is null");
            return (Criteria) this;
        }

        public Criteria andSpeExetimeIsNotNull() {
            addCriterion("spe_exeTime is not null");
            return (Criteria) this;
        }

        public Criteria andSpeExetimeEqualTo(Date value) {
            addCriterion("spe_exeTime =", value, "speExetime");
            return (Criteria) this;
        }

        public Criteria andSpeExetimeNotEqualTo(Date value) {
            addCriterion("spe_exeTime <>", value, "speExetime");
            return (Criteria) this;
        }

        public Criteria andSpeExetimeGreaterThan(Date value) {
            addCriterion("spe_exeTime >", value, "speExetime");
            return (Criteria) this;
        }

        public Criteria andSpeExetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("spe_exeTime >=", value, "speExetime");
            return (Criteria) this;
        }

        public Criteria andSpeExetimeLessThan(Date value) {
            addCriterion("spe_exeTime <", value, "speExetime");
            return (Criteria) this;
        }

        public Criteria andSpeExetimeLessThanOrEqualTo(Date value) {
            addCriterion("spe_exeTime <=", value, "speExetime");
            return (Criteria) this;
        }

        public Criteria andSpeExetimeIn(List<Date> values) {
            addCriterion("spe_exeTime in", values, "speExetime");
            return (Criteria) this;
        }

        public Criteria andSpeExetimeNotIn(List<Date> values) {
            addCriterion("spe_exeTime not in", values, "speExetime");
            return (Criteria) this;
        }

        public Criteria andSpeExetimeBetween(Date value1, Date value2) {
            addCriterion("spe_exeTime between", value1, value2, "speExetime");
            return (Criteria) this;
        }

        public Criteria andSpeExetimeNotBetween(Date value1, Date value2) {
            addCriterion("spe_exeTime not between", value1, value2, "speExetime");
            return (Criteria) this;
        }

        public Criteria andSpeCreatetimeIsNull() {
            addCriterion("spe_createTime is null");
            return (Criteria) this;
        }

        public Criteria andSpeCreatetimeIsNotNull() {
            addCriterion("spe_createTime is not null");
            return (Criteria) this;
        }

        public Criteria andSpeCreatetimeEqualTo(Date value) {
            addCriterion("spe_createTime =", value, "speCreatetime");
            return (Criteria) this;
        }

        public Criteria andSpeCreatetimeNotEqualTo(Date value) {
            addCriterion("spe_createTime <>", value, "speCreatetime");
            return (Criteria) this;
        }

        public Criteria andSpeCreatetimeGreaterThan(Date value) {
            addCriterion("spe_createTime >", value, "speCreatetime");
            return (Criteria) this;
        }

        public Criteria andSpeCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("spe_createTime >=", value, "speCreatetime");
            return (Criteria) this;
        }

        public Criteria andSpeCreatetimeLessThan(Date value) {
            addCriterion("spe_createTime <", value, "speCreatetime");
            return (Criteria) this;
        }

        public Criteria andSpeCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("spe_createTime <=", value, "speCreatetime");
            return (Criteria) this;
        }

        public Criteria andSpeCreatetimeIn(List<Date> values) {
            addCriterion("spe_createTime in", values, "speCreatetime");
            return (Criteria) this;
        }

        public Criteria andSpeCreatetimeNotIn(List<Date> values) {
            addCriterion("spe_createTime not in", values, "speCreatetime");
            return (Criteria) this;
        }

        public Criteria andSpeCreatetimeBetween(Date value1, Date value2) {
            addCriterion("spe_createTime between", value1, value2, "speCreatetime");
            return (Criteria) this;
        }

        public Criteria andSpeCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("spe_createTime not between", value1, value2, "speCreatetime");
            return (Criteria) this;
        }

        public Criteria andSpePidIsNull() {
            addCriterion("spe_pId is null");
            return (Criteria) this;
        }

        public Criteria andSpePidIsNotNull() {
            addCriterion("spe_pId is not null");
            return (Criteria) this;
        }

        public Criteria andSpePidEqualTo(Integer value) {
            addCriterion("spe_pId =", value, "spePid");
            return (Criteria) this;
        }

        public Criteria andSpePidNotEqualTo(Integer value) {
            addCriterion("spe_pId <>", value, "spePid");
            return (Criteria) this;
        }

        public Criteria andSpePidGreaterThan(Integer value) {
            addCriterion("spe_pId >", value, "spePid");
            return (Criteria) this;
        }

        public Criteria andSpePidGreaterThanOrEqualTo(Integer value) {
            addCriterion("spe_pId >=", value, "spePid");
            return (Criteria) this;
        }

        public Criteria andSpePidLessThan(Integer value) {
            addCriterion("spe_pId <", value, "spePid");
            return (Criteria) this;
        }

        public Criteria andSpePidLessThanOrEqualTo(Integer value) {
            addCriterion("spe_pId <=", value, "spePid");
            return (Criteria) this;
        }

        public Criteria andSpePidIn(List<Integer> values) {
            addCriterion("spe_pId in", values, "spePid");
            return (Criteria) this;
        }

        public Criteria andSpePidNotIn(List<Integer> values) {
            addCriterion("spe_pId not in", values, "spePid");
            return (Criteria) this;
        }

        public Criteria andSpePidBetween(Integer value1, Integer value2) {
            addCriterion("spe_pId between", value1, value2, "spePid");
            return (Criteria) this;
        }

        public Criteria andSpePidNotBetween(Integer value1, Integer value2) {
            addCriterion("spe_pId not between", value1, value2, "spePid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sale_plan_exe
     *
     * @mbg.generated do_not_delete_during_merge Mon Sep 30 11:43:00 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sale_plan_exe
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}