package com.luckylas.crm.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SaleChanceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sale_chance
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sale_chance
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sale_chance
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public SaleChanceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sale_chance
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andScIdIsNull() {
            addCriterion("sc_id is null");
            return (Criteria) this;
        }

        public Criteria andScIdIsNotNull() {
            addCriterion("sc_id is not null");
            return (Criteria) this;
        }

        public Criteria andScIdEqualTo(Integer value) {
            addCriterion("sc_id =", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdNotEqualTo(Integer value) {
            addCriterion("sc_id <>", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdGreaterThan(Integer value) {
            addCriterion("sc_id >", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sc_id >=", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdLessThan(Integer value) {
            addCriterion("sc_id <", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdLessThanOrEqualTo(Integer value) {
            addCriterion("sc_id <=", value, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdIn(List<Integer> values) {
            addCriterion("sc_id in", values, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdNotIn(List<Integer> values) {
            addCriterion("sc_id not in", values, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdBetween(Integer value1, Integer value2) {
            addCriterion("sc_id between", value1, value2, "scId");
            return (Criteria) this;
        }

        public Criteria andScIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sc_id not between", value1, value2, "scId");
            return (Criteria) this;
        }

        public Criteria andScCusnameIsNull() {
            addCriterion("sc_cusName is null");
            return (Criteria) this;
        }

        public Criteria andScCusnameIsNotNull() {
            addCriterion("sc_cusName is not null");
            return (Criteria) this;
        }

        public Criteria andScCusnameEqualTo(String value) {
            addCriterion("sc_cusName =", value, "scCusname");
            return (Criteria) this;
        }

        public Criteria andScCusnameNotEqualTo(String value) {
            addCriterion("sc_cusName <>", value, "scCusname");
            return (Criteria) this;
        }

        public Criteria andScCusnameGreaterThan(String value) {
            addCriterion("sc_cusName >", value, "scCusname");
            return (Criteria) this;
        }

        public Criteria andScCusnameGreaterThanOrEqualTo(String value) {
            addCriterion("sc_cusName >=", value, "scCusname");
            return (Criteria) this;
        }

        public Criteria andScCusnameLessThan(String value) {
            addCriterion("sc_cusName <", value, "scCusname");
            return (Criteria) this;
        }

        public Criteria andScCusnameLessThanOrEqualTo(String value) {
            addCriterion("sc_cusName <=", value, "scCusname");
            return (Criteria) this;
        }

        public Criteria andScCusnameLike(String value) {
            addCriterion("sc_cusName like", value, "scCusname");
            return (Criteria) this;
        }

        public Criteria andScCusnameNotLike(String value) {
            addCriterion("sc_cusName not like", value, "scCusname");
            return (Criteria) this;
        }

        public Criteria andScCusnameIn(List<String> values) {
            addCriterion("sc_cusName in", values, "scCusname");
            return (Criteria) this;
        }

        public Criteria andScCusnameNotIn(List<String> values) {
            addCriterion("sc_cusName not in", values, "scCusname");
            return (Criteria) this;
        }

        public Criteria andScCusnameBetween(String value1, String value2) {
            addCriterion("sc_cusName between", value1, value2, "scCusname");
            return (Criteria) this;
        }

        public Criteria andScCusnameNotBetween(String value1, String value2) {
            addCriterion("sc_cusName not between", value1, value2, "scCusname");
            return (Criteria) this;
        }

        public Criteria andScCommingIsNull() {
            addCriterion("sc_comming is null");
            return (Criteria) this;
        }

        public Criteria andScCommingIsNotNull() {
            addCriterion("sc_comming is not null");
            return (Criteria) this;
        }

        public Criteria andScCommingEqualTo(String value) {
            addCriterion("sc_comming =", value, "scComming");
            return (Criteria) this;
        }

        public Criteria andScCommingNotEqualTo(String value) {
            addCriterion("sc_comming <>", value, "scComming");
            return (Criteria) this;
        }

        public Criteria andScCommingGreaterThan(String value) {
            addCriterion("sc_comming >", value, "scComming");
            return (Criteria) this;
        }

        public Criteria andScCommingGreaterThanOrEqualTo(String value) {
            addCriterion("sc_comming >=", value, "scComming");
            return (Criteria) this;
        }

        public Criteria andScCommingLessThan(String value) {
            addCriterion("sc_comming <", value, "scComming");
            return (Criteria) this;
        }

        public Criteria andScCommingLessThanOrEqualTo(String value) {
            addCriterion("sc_comming <=", value, "scComming");
            return (Criteria) this;
        }

        public Criteria andScCommingLike(String value) {
            addCriterion("sc_comming like", value, "scComming");
            return (Criteria) this;
        }

        public Criteria andScCommingNotLike(String value) {
            addCriterion("sc_comming not like", value, "scComming");
            return (Criteria) this;
        }

        public Criteria andScCommingIn(List<String> values) {
            addCriterion("sc_comming in", values, "scComming");
            return (Criteria) this;
        }

        public Criteria andScCommingNotIn(List<String> values) {
            addCriterion("sc_comming not in", values, "scComming");
            return (Criteria) this;
        }

        public Criteria andScCommingBetween(String value1, String value2) {
            addCriterion("sc_comming between", value1, value2, "scComming");
            return (Criteria) this;
        }

        public Criteria andScCommingNotBetween(String value1, String value2) {
            addCriterion("sc_comming not between", value1, value2, "scComming");
            return (Criteria) this;
        }

        public Criteria andScConnameIsNull() {
            addCriterion("sc_conName is null");
            return (Criteria) this;
        }

        public Criteria andScConnameIsNotNull() {
            addCriterion("sc_conName is not null");
            return (Criteria) this;
        }

        public Criteria andScConnameEqualTo(String value) {
            addCriterion("sc_conName =", value, "scConname");
            return (Criteria) this;
        }

        public Criteria andScConnameNotEqualTo(String value) {
            addCriterion("sc_conName <>", value, "scConname");
            return (Criteria) this;
        }

        public Criteria andScConnameGreaterThan(String value) {
            addCriterion("sc_conName >", value, "scConname");
            return (Criteria) this;
        }

        public Criteria andScConnameGreaterThanOrEqualTo(String value) {
            addCriterion("sc_conName >=", value, "scConname");
            return (Criteria) this;
        }

        public Criteria andScConnameLessThan(String value) {
            addCriterion("sc_conName <", value, "scConname");
            return (Criteria) this;
        }

        public Criteria andScConnameLessThanOrEqualTo(String value) {
            addCriterion("sc_conName <=", value, "scConname");
            return (Criteria) this;
        }

        public Criteria andScConnameLike(String value) {
            addCriterion("sc_conName like", value, "scConname");
            return (Criteria) this;
        }

        public Criteria andScConnameNotLike(String value) {
            addCriterion("sc_conName not like", value, "scConname");
            return (Criteria) this;
        }

        public Criteria andScConnameIn(List<String> values) {
            addCriterion("sc_conName in", values, "scConname");
            return (Criteria) this;
        }

        public Criteria andScConnameNotIn(List<String> values) {
            addCriterion("sc_conName not in", values, "scConname");
            return (Criteria) this;
        }

        public Criteria andScConnameBetween(String value1, String value2) {
            addCriterion("sc_conName between", value1, value2, "scConname");
            return (Criteria) this;
        }

        public Criteria andScConnameNotBetween(String value1, String value2) {
            addCriterion("sc_conName not between", value1, value2, "scConname");
            return (Criteria) this;
        }

        public Criteria andScConphoneIsNull() {
            addCriterion("sc_conPhone is null");
            return (Criteria) this;
        }

        public Criteria andScConphoneIsNotNull() {
            addCriterion("sc_conPhone is not null");
            return (Criteria) this;
        }

        public Criteria andScConphoneEqualTo(String value) {
            addCriterion("sc_conPhone =", value, "scConphone");
            return (Criteria) this;
        }

        public Criteria andScConphoneNotEqualTo(String value) {
            addCriterion("sc_conPhone <>", value, "scConphone");
            return (Criteria) this;
        }

        public Criteria andScConphoneGreaterThan(String value) {
            addCriterion("sc_conPhone >", value, "scConphone");
            return (Criteria) this;
        }

        public Criteria andScConphoneGreaterThanOrEqualTo(String value) {
            addCriterion("sc_conPhone >=", value, "scConphone");
            return (Criteria) this;
        }

        public Criteria andScConphoneLessThan(String value) {
            addCriterion("sc_conPhone <", value, "scConphone");
            return (Criteria) this;
        }

        public Criteria andScConphoneLessThanOrEqualTo(String value) {
            addCriterion("sc_conPhone <=", value, "scConphone");
            return (Criteria) this;
        }

        public Criteria andScConphoneLike(String value) {
            addCriterion("sc_conPhone like", value, "scConphone");
            return (Criteria) this;
        }

        public Criteria andScConphoneNotLike(String value) {
            addCriterion("sc_conPhone not like", value, "scConphone");
            return (Criteria) this;
        }

        public Criteria andScConphoneIn(List<String> values) {
            addCriterion("sc_conPhone in", values, "scConphone");
            return (Criteria) this;
        }

        public Criteria andScConphoneNotIn(List<String> values) {
            addCriterion("sc_conPhone not in", values, "scConphone");
            return (Criteria) this;
        }

        public Criteria andScConphoneBetween(String value1, String value2) {
            addCriterion("sc_conPhone between", value1, value2, "scConphone");
            return (Criteria) this;
        }

        public Criteria andScConphoneNotBetween(String value1, String value2) {
            addCriterion("sc_conPhone not between", value1, value2, "scConphone");
            return (Criteria) this;
        }

        public Criteria andScSuccessIsNull() {
            addCriterion("sc_success is null");
            return (Criteria) this;
        }

        public Criteria andScSuccessIsNotNull() {
            addCriterion("sc_success is not null");
            return (Criteria) this;
        }

        public Criteria andScSuccessEqualTo(String value) {
            addCriterion("sc_success =", value, "scSuccess");
            return (Criteria) this;
        }

        public Criteria andScSuccessNotEqualTo(String value) {
            addCriterion("sc_success <>", value, "scSuccess");
            return (Criteria) this;
        }

        public Criteria andScSuccessGreaterThan(String value) {
            addCriterion("sc_success >", value, "scSuccess");
            return (Criteria) this;
        }

        public Criteria andScSuccessGreaterThanOrEqualTo(String value) {
            addCriterion("sc_success >=", value, "scSuccess");
            return (Criteria) this;
        }

        public Criteria andScSuccessLessThan(String value) {
            addCriterion("sc_success <", value, "scSuccess");
            return (Criteria) this;
        }

        public Criteria andScSuccessLessThanOrEqualTo(String value) {
            addCriterion("sc_success <=", value, "scSuccess");
            return (Criteria) this;
        }

        public Criteria andScSuccessLike(String value) {
            addCriterion("sc_success like", value, "scSuccess");
            return (Criteria) this;
        }

        public Criteria andScSuccessNotLike(String value) {
            addCriterion("sc_success not like", value, "scSuccess");
            return (Criteria) this;
        }

        public Criteria andScSuccessIn(List<String> values) {
            addCriterion("sc_success in", values, "scSuccess");
            return (Criteria) this;
        }

        public Criteria andScSuccessNotIn(List<String> values) {
            addCriterion("sc_success not in", values, "scSuccess");
            return (Criteria) this;
        }

        public Criteria andScSuccessBetween(String value1, String value2) {
            addCriterion("sc_success between", value1, value2, "scSuccess");
            return (Criteria) this;
        }

        public Criteria andScSuccessNotBetween(String value1, String value2) {
            addCriterion("sc_success not between", value1, value2, "scSuccess");
            return (Criteria) this;
        }

        public Criteria andScDescIsNull() {
            addCriterion("sc_desc is null");
            return (Criteria) this;
        }

        public Criteria andScDescIsNotNull() {
            addCriterion("sc_desc is not null");
            return (Criteria) this;
        }

        public Criteria andScDescEqualTo(String value) {
            addCriterion("sc_desc =", value, "scDesc");
            return (Criteria) this;
        }

        public Criteria andScDescNotEqualTo(String value) {
            addCriterion("sc_desc <>", value, "scDesc");
            return (Criteria) this;
        }

        public Criteria andScDescGreaterThan(String value) {
            addCriterion("sc_desc >", value, "scDesc");
            return (Criteria) this;
        }

        public Criteria andScDescGreaterThanOrEqualTo(String value) {
            addCriterion("sc_desc >=", value, "scDesc");
            return (Criteria) this;
        }

        public Criteria andScDescLessThan(String value) {
            addCriterion("sc_desc <", value, "scDesc");
            return (Criteria) this;
        }

        public Criteria andScDescLessThanOrEqualTo(String value) {
            addCriterion("sc_desc <=", value, "scDesc");
            return (Criteria) this;
        }

        public Criteria andScDescLike(String value) {
            addCriterion("sc_desc like", value, "scDesc");
            return (Criteria) this;
        }

        public Criteria andScDescNotLike(String value) {
            addCriterion("sc_desc not like", value, "scDesc");
            return (Criteria) this;
        }

        public Criteria andScDescIn(List<String> values) {
            addCriterion("sc_desc in", values, "scDesc");
            return (Criteria) this;
        }

        public Criteria andScDescNotIn(List<String> values) {
            addCriterion("sc_desc not in", values, "scDesc");
            return (Criteria) this;
        }

        public Criteria andScDescBetween(String value1, String value2) {
            addCriterion("sc_desc between", value1, value2, "scDesc");
            return (Criteria) this;
        }

        public Criteria andScDescNotBetween(String value1, String value2) {
            addCriterion("sc_desc not between", value1, value2, "scDesc");
            return (Criteria) this;
        }

        public Criteria andScCreateuidIsNull() {
            addCriterion("sc_createUId is null");
            return (Criteria) this;
        }

        public Criteria andScCreateuidIsNotNull() {
            addCriterion("sc_createUId is not null");
            return (Criteria) this;
        }

        public Criteria andScCreateuidEqualTo(Integer value) {
            addCriterion("sc_createUId =", value, "scCreateuid");
            return (Criteria) this;
        }

        public Criteria andScCreateuidNotEqualTo(Integer value) {
            addCriterion("sc_createUId <>", value, "scCreateuid");
            return (Criteria) this;
        }

        public Criteria andScCreateuidGreaterThan(Integer value) {
            addCriterion("sc_createUId >", value, "scCreateuid");
            return (Criteria) this;
        }

        public Criteria andScCreateuidGreaterThanOrEqualTo(Integer value) {
            addCriterion("sc_createUId >=", value, "scCreateuid");
            return (Criteria) this;
        }

        public Criteria andScCreateuidLessThan(Integer value) {
            addCriterion("sc_createUId <", value, "scCreateuid");
            return (Criteria) this;
        }

        public Criteria andScCreateuidLessThanOrEqualTo(Integer value) {
            addCriterion("sc_createUId <=", value, "scCreateuid");
            return (Criteria) this;
        }

        public Criteria andScCreateuidIn(List<Integer> values) {
            addCriterion("sc_createUId in", values, "scCreateuid");
            return (Criteria) this;
        }

        public Criteria andScCreateuidNotIn(List<Integer> values) {
            addCriterion("sc_createUId not in", values, "scCreateuid");
            return (Criteria) this;
        }

        public Criteria andScCreateuidBetween(Integer value1, Integer value2) {
            addCriterion("sc_createUId between", value1, value2, "scCreateuid");
            return (Criteria) this;
        }

        public Criteria andScCreateuidNotBetween(Integer value1, Integer value2) {
            addCriterion("sc_createUId not between", value1, value2, "scCreateuid");
            return (Criteria) this;
        }

        public Criteria andScCreateunameIsNull() {
            addCriterion("sc_createUName is null");
            return (Criteria) this;
        }

        public Criteria andScCreateunameIsNotNull() {
            addCriterion("sc_createUName is not null");
            return (Criteria) this;
        }

        public Criteria andScCreateunameEqualTo(String value) {
            addCriterion("sc_createUName =", value, "scCreateuname");
            return (Criteria) this;
        }

        public Criteria andScCreateunameNotEqualTo(String value) {
            addCriterion("sc_createUName <>", value, "scCreateuname");
            return (Criteria) this;
        }

        public Criteria andScCreateunameGreaterThan(String value) {
            addCriterion("sc_createUName >", value, "scCreateuname");
            return (Criteria) this;
        }

        public Criteria andScCreateunameGreaterThanOrEqualTo(String value) {
            addCriterion("sc_createUName >=", value, "scCreateuname");
            return (Criteria) this;
        }

        public Criteria andScCreateunameLessThan(String value) {
            addCriterion("sc_createUName <", value, "scCreateuname");
            return (Criteria) this;
        }

        public Criteria andScCreateunameLessThanOrEqualTo(String value) {
            addCriterion("sc_createUName <=", value, "scCreateuname");
            return (Criteria) this;
        }

        public Criteria andScCreateunameLike(String value) {
            addCriterion("sc_createUName like", value, "scCreateuname");
            return (Criteria) this;
        }

        public Criteria andScCreateunameNotLike(String value) {
            addCriterion("sc_createUName not like", value, "scCreateuname");
            return (Criteria) this;
        }

        public Criteria andScCreateunameIn(List<String> values) {
            addCriterion("sc_createUName in", values, "scCreateuname");
            return (Criteria) this;
        }

        public Criteria andScCreateunameNotIn(List<String> values) {
            addCriterion("sc_createUName not in", values, "scCreateuname");
            return (Criteria) this;
        }

        public Criteria andScCreateunameBetween(String value1, String value2) {
            addCriterion("sc_createUName between", value1, value2, "scCreateuname");
            return (Criteria) this;
        }

        public Criteria andScCreateunameNotBetween(String value1, String value2) {
            addCriterion("sc_createUName not between", value1, value2, "scCreateuname");
            return (Criteria) this;
        }

        public Criteria andScCreatetimeIsNull() {
            addCriterion("sc_createTime is null");
            return (Criteria) this;
        }

        public Criteria andScCreatetimeIsNotNull() {
            addCriterion("sc_createTime is not null");
            return (Criteria) this;
        }

        public Criteria andScCreatetimeEqualTo(Date value) {
            addCriterion("sc_createTime =", value, "scCreatetime");
            return (Criteria) this;
        }

        public Criteria andScCreatetimeNotEqualTo(Date value) {
            addCriterion("sc_createTime <>", value, "scCreatetime");
            return (Criteria) this;
        }

        public Criteria andScCreatetimeGreaterThan(Date value) {
            addCriterion("sc_createTime >", value, "scCreatetime");
            return (Criteria) this;
        }

        public Criteria andScCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sc_createTime >=", value, "scCreatetime");
            return (Criteria) this;
        }

        public Criteria andScCreatetimeLessThan(Date value) {
            addCriterion("sc_createTime <", value, "scCreatetime");
            return (Criteria) this;
        }

        public Criteria andScCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("sc_createTime <=", value, "scCreatetime");
            return (Criteria) this;
        }

        public Criteria andScCreatetimeIn(List<Date> values) {
            addCriterion("sc_createTime in", values, "scCreatetime");
            return (Criteria) this;
        }

        public Criteria andScCreatetimeNotIn(List<Date> values) {
            addCriterion("sc_createTime not in", values, "scCreatetime");
            return (Criteria) this;
        }

        public Criteria andScCreatetimeBetween(Date value1, Date value2) {
            addCriterion("sc_createTime between", value1, value2, "scCreatetime");
            return (Criteria) this;
        }

        public Criteria andScCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("sc_createTime not between", value1, value2, "scCreatetime");
            return (Criteria) this;
        }

        public Criteria andScGiveuidIsNull() {
            addCriterion("sc_giveUId is null");
            return (Criteria) this;
        }

        public Criteria andScGiveuidIsNotNull() {
            addCriterion("sc_giveUId is not null");
            return (Criteria) this;
        }

        public Criteria andScGiveuidEqualTo(Integer value) {
            addCriterion("sc_giveUId =", value, "scGiveuid");
            return (Criteria) this;
        }

        public Criteria andScGiveuidNotEqualTo(Integer value) {
            addCriterion("sc_giveUId <>", value, "scGiveuid");
            return (Criteria) this;
        }

        public Criteria andScGiveuidGreaterThan(Integer value) {
            addCriterion("sc_giveUId >", value, "scGiveuid");
            return (Criteria) this;
        }

        public Criteria andScGiveuidGreaterThanOrEqualTo(Integer value) {
            addCriterion("sc_giveUId >=", value, "scGiveuid");
            return (Criteria) this;
        }

        public Criteria andScGiveuidLessThan(Integer value) {
            addCriterion("sc_giveUId <", value, "scGiveuid");
            return (Criteria) this;
        }

        public Criteria andScGiveuidLessThanOrEqualTo(Integer value) {
            addCriterion("sc_giveUId <=", value, "scGiveuid");
            return (Criteria) this;
        }

        public Criteria andScGiveuidIn(List<Integer> values) {
            addCriterion("sc_giveUId in", values, "scGiveuid");
            return (Criteria) this;
        }

        public Criteria andScGiveuidNotIn(List<Integer> values) {
            addCriterion("sc_giveUId not in", values, "scGiveuid");
            return (Criteria) this;
        }

        public Criteria andScGiveuidBetween(Integer value1, Integer value2) {
            addCriterion("sc_giveUId between", value1, value2, "scGiveuid");
            return (Criteria) this;
        }

        public Criteria andScGiveuidNotBetween(Integer value1, Integer value2) {
            addCriterion("sc_giveUId not between", value1, value2, "scGiveuid");
            return (Criteria) this;
        }

        public Criteria andScGiveunameIsNull() {
            addCriterion("sc_giveUName is null");
            return (Criteria) this;
        }

        public Criteria andScGiveunameIsNotNull() {
            addCriterion("sc_giveUName is not null");
            return (Criteria) this;
        }

        public Criteria andScGiveunameEqualTo(String value) {
            addCriterion("sc_giveUName =", value, "scGiveuname");
            return (Criteria) this;
        }

        public Criteria andScGiveunameNotEqualTo(String value) {
            addCriterion("sc_giveUName <>", value, "scGiveuname");
            return (Criteria) this;
        }

        public Criteria andScGiveunameGreaterThan(String value) {
            addCriterion("sc_giveUName >", value, "scGiveuname");
            return (Criteria) this;
        }

        public Criteria andScGiveunameGreaterThanOrEqualTo(String value) {
            addCriterion("sc_giveUName >=", value, "scGiveuname");
            return (Criteria) this;
        }

        public Criteria andScGiveunameLessThan(String value) {
            addCriterion("sc_giveUName <", value, "scGiveuname");
            return (Criteria) this;
        }

        public Criteria andScGiveunameLessThanOrEqualTo(String value) {
            addCriterion("sc_giveUName <=", value, "scGiveuname");
            return (Criteria) this;
        }

        public Criteria andScGiveunameLike(String value) {
            addCriterion("sc_giveUName like", value, "scGiveuname");
            return (Criteria) this;
        }

        public Criteria andScGiveunameNotLike(String value) {
            addCriterion("sc_giveUName not like", value, "scGiveuname");
            return (Criteria) this;
        }

        public Criteria andScGiveunameIn(List<String> values) {
            addCriterion("sc_giveUName in", values, "scGiveuname");
            return (Criteria) this;
        }

        public Criteria andScGiveunameNotIn(List<String> values) {
            addCriterion("sc_giveUName not in", values, "scGiveuname");
            return (Criteria) this;
        }

        public Criteria andScGiveunameBetween(String value1, String value2) {
            addCriterion("sc_giveUName between", value1, value2, "scGiveuname");
            return (Criteria) this;
        }

        public Criteria andScGiveunameNotBetween(String value1, String value2) {
            addCriterion("sc_giveUName not between", value1, value2, "scGiveuname");
            return (Criteria) this;
        }

        public Criteria andScGivetimeIsNull() {
            addCriterion("sc_giveTime is null");
            return (Criteria) this;
        }

        public Criteria andScGivetimeIsNotNull() {
            addCriterion("sc_giveTime is not null");
            return (Criteria) this;
        }

        public Criteria andScGivetimeEqualTo(Date value) {
            addCriterion("sc_giveTime =", value, "scGivetime");
            return (Criteria) this;
        }

        public Criteria andScGivetimeNotEqualTo(Date value) {
            addCriterion("sc_giveTime <>", value, "scGivetime");
            return (Criteria) this;
        }

        public Criteria andScGivetimeGreaterThan(Date value) {
            addCriterion("sc_giveTime >", value, "scGivetime");
            return (Criteria) this;
        }

        public Criteria andScGivetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sc_giveTime >=", value, "scGivetime");
            return (Criteria) this;
        }

        public Criteria andScGivetimeLessThan(Date value) {
            addCriterion("sc_giveTime <", value, "scGivetime");
            return (Criteria) this;
        }

        public Criteria andScGivetimeLessThanOrEqualTo(Date value) {
            addCriterion("sc_giveTime <=", value, "scGivetime");
            return (Criteria) this;
        }

        public Criteria andScGivetimeIn(List<Date> values) {
            addCriterion("sc_giveTime in", values, "scGivetime");
            return (Criteria) this;
        }

        public Criteria andScGivetimeNotIn(List<Date> values) {
            addCriterion("sc_giveTime not in", values, "scGivetime");
            return (Criteria) this;
        }

        public Criteria andScGivetimeBetween(Date value1, Date value2) {
            addCriterion("sc_giveTime between", value1, value2, "scGivetime");
            return (Criteria) this;
        }

        public Criteria andScGivetimeNotBetween(Date value1, Date value2) {
            addCriterion("sc_giveTime not between", value1, value2, "scGivetime");
            return (Criteria) this;
        }

        public Criteria andScStatusIsNull() {
            addCriterion("sc_status is null");
            return (Criteria) this;
        }

        public Criteria andScStatusIsNotNull() {
            addCriterion("sc_status is not null");
            return (Criteria) this;
        }

        public Criteria andScStatusEqualTo(Integer value) {
            addCriterion("sc_status =", value, "scStatus");
            return (Criteria) this;
        }

        public Criteria andScStatusNotEqualTo(Integer value) {
            addCriterion("sc_status <>", value, "scStatus");
            return (Criteria) this;
        }

        public Criteria andScStatusGreaterThan(Integer value) {
            addCriterion("sc_status >", value, "scStatus");
            return (Criteria) this;
        }

        public Criteria andScStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("sc_status >=", value, "scStatus");
            return (Criteria) this;
        }

        public Criteria andScStatusLessThan(Integer value) {
            addCriterion("sc_status <", value, "scStatus");
            return (Criteria) this;
        }

        public Criteria andScStatusLessThanOrEqualTo(Integer value) {
            addCriterion("sc_status <=", value, "scStatus");
            return (Criteria) this;
        }

        public Criteria andScStatusIn(List<Integer> values) {
            addCriterion("sc_status in", values, "scStatus");
            return (Criteria) this;
        }

        public Criteria andScStatusNotIn(List<Integer> values) {
            addCriterion("sc_status not in", values, "scStatus");
            return (Criteria) this;
        }

        public Criteria andScStatusBetween(Integer value1, Integer value2) {
            addCriterion("sc_status between", value1, value2, "scStatus");
            return (Criteria) this;
        }

        public Criteria andScStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("sc_status not between", value1, value2, "scStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sale_chance
     *
     * @mbg.generated do_not_delete_during_merge Mon Sep 30 13:48:58 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sale_chance
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}