package com.luckylas.crm.entity;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * 销售机会实体类
 * @author luckyliuqs
 *
 */
public class SaleChance {
    /**
     * 销售机会id
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.sc_id
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    private Integer scId;

    /**
     * 客户名称
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.sc_cusName
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    private String scCusname;

    /**
     * 销售机会来源
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.sc_comming
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    private String scComming;

    /**
     * 联系人
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.sc_conName
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    private String scConname;

    /**
     * 联系人电话
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.sc_conPhone
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    private String scConphone;

    /**
     * 成功率
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.sc_success
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    private String scSuccess;

    /**
     * 销售机会描述
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.sc_desc
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    private String scDesc;

    /**
     * 创建销售机会的用户id
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.sc_createUId
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    private Integer scCreateuid;

    /**
     * 创建销售机会的用户姓名
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.sc_createUName
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    private String scCreateuname;

    /**
     * 创建销售机会时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.sc_createTime
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date scCreatetime;

    /**
     * 分配销售机会给指定id的用户
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.sc_giveUId
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    private Integer scGiveuid;

    /**
     * 分配销售机会给指定姓名的用户
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.sc_giveUName
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    private String scGiveuname;

    /**
     * 分配销售机会时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.sc_giveTime
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date scGivetime;

    /**
     * 销售机会状态：0-未分配，1-已分配但未开发，2-正在开发，3-开发失败，4-开发成功
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_chance.sc_status
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    private Integer scStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.sc_id
     *
     * @return the value of sale_chance.sc_id
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public Integer getScId() {
        return scId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.sc_id
     *
     * @param scId the value for sale_chance.sc_id
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public void setScId(Integer scId) {
        this.scId = scId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.sc_cusName
     *
     * @return the value of sale_chance.sc_cusName
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public String getScCusname() {
        return scCusname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.sc_cusName
     *
     * @param scCusname the value for sale_chance.sc_cusName
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public void setScCusname(String scCusname) {
        this.scCusname = scCusname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.sc_comming
     *
     * @return the value of sale_chance.sc_comming
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public String getScComming() {
        return scComming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.sc_comming
     *
     * @param scComming the value for sale_chance.sc_comming
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public void setScComming(String scComming) {
        this.scComming = scComming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.sc_conName
     *
     * @return the value of sale_chance.sc_conName
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public String getScConname() {
        return scConname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.sc_conName
     *
     * @param scConname the value for sale_chance.sc_conName
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public void setScConname(String scConname) {
        this.scConname = scConname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.sc_conPhone
     *
     * @return the value of sale_chance.sc_conPhone
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public String getScConphone() {
        return scConphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.sc_conPhone
     *
     * @param scConphone the value for sale_chance.sc_conPhone
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public void setScConphone(String scConphone) {
        this.scConphone = scConphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.sc_success
     *
     * @return the value of sale_chance.sc_success
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public String getScSuccess() {
        return scSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.sc_success
     *
     * @param scSuccess the value for sale_chance.sc_success
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public void setScSuccess(String scSuccess) {
        this.scSuccess = scSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.sc_desc
     *
     * @return the value of sale_chance.sc_desc
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public String getScDesc() {
        return scDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.sc_desc
     *
     * @param scDesc the value for sale_chance.sc_desc
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public void setScDesc(String scDesc) {
        this.scDesc = scDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.sc_createUId
     *
     * @return the value of sale_chance.sc_createUId
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public Integer getScCreateuid() {
        return scCreateuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.sc_createUId
     *
     * @param scCreateuid the value for sale_chance.sc_createUId
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public void setScCreateuid(Integer scCreateuid) {
        this.scCreateuid = scCreateuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.sc_createUName
     *
     * @return the value of sale_chance.sc_createUName
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public String getScCreateuname() {
        return scCreateuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.sc_createUName
     *
     * @param scCreateuname the value for sale_chance.sc_createUName
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public void setScCreateuname(String scCreateuname) {
        this.scCreateuname = scCreateuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.sc_createTime
     *
     * @return the value of sale_chance.sc_createTime
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public Date getScCreatetime() {
        return scCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.sc_createTime
     *
     * @param scCreatetime the value for sale_chance.sc_createTime
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public void setScCreatetime(Date scCreatetime) {
        this.scCreatetime = scCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.sc_giveUId
     *
     * @return the value of sale_chance.sc_giveUId
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public Integer getScGiveuid() {
        return scGiveuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.sc_giveUId
     *
     * @param scGiveuid the value for sale_chance.sc_giveUId
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public void setScGiveuid(Integer scGiveuid) {
        this.scGiveuid = scGiveuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.sc_giveUName
     *
     * @return the value of sale_chance.sc_giveUName
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public String getScGiveuname() {
        return scGiveuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.sc_giveUName
     *
     * @param scGiveuname the value for sale_chance.sc_giveUName
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public void setScGiveuname(String scGiveuname) {
        this.scGiveuname = scGiveuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.sc_giveTime
     *
     * @return the value of sale_chance.sc_giveTime
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public Date getScGivetime() {
        return scGivetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.sc_giveTime
     *
     * @param scGivetime the value for sale_chance.sc_giveTime
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public void setScGivetime(Date scGivetime) {
        this.scGivetime = scGivetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_chance.sc_status
     *
     * @return the value of sale_chance.sc_status
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public Integer getScStatus() {
        return scStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_chance.sc_status
     *
     * @param scStatus the value for sale_chance.sc_status
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    public void setScStatus(Integer scStatus) {
        this.scStatus = scStatus;
    }

	@Override
	public String toString() {
		return "SaleChance [scId=" + scId + "," + scGiveuid +
				 ", scStatus=" + scStatus + "]";
	}
    
}