package com.luckylas.crm.entity;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * 销售计划执行实体类
 * @author luckyliuqs
 *
 */
public class SalePlanExe {
    /**
     * id
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_plan_exe.spe_id
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    private Integer speId;

    /**
     * 执行情况
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_plan_exe.spe_exeCase
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    private String speExecase;

    /**
     * 执行时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_plan_exe.spe_exeTime
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date speExetime;

    /**
     * 创建时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_plan_exe.spe_createTime
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date speCreatetime;

    /**
     * 销售计划id
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_plan_exe.spe_pId
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    private Integer spePid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_plan_exe.spe_id
     *
     * @return the value of sale_plan_exe.spe_id
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    public Integer getSpeId() {
        return speId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_plan_exe.spe_id
     *
     * @param speId the value for sale_plan_exe.spe_id
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    public void setSpeId(Integer speId) {
        this.speId = speId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_plan_exe.spe_exeCase
     *
     * @return the value of sale_plan_exe.spe_exeCase
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    public String getSpeExecase() {
        return speExecase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_plan_exe.spe_exeCase
     *
     * @param speExecase the value for sale_plan_exe.spe_exeCase
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    public void setSpeExecase(String speExecase) {
        this.speExecase = speExecase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_plan_exe.spe_exeTime
     *
     * @return the value of sale_plan_exe.spe_exeTime
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    public Date getSpeExetime() {
        return speExetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_plan_exe.spe_exeTime
     *
     * @param speExetime the value for sale_plan_exe.spe_exeTime
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    public void setSpeExetime(Date speExetime) {
        this.speExetime = speExetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_plan_exe.spe_createTime
     *
     * @return the value of sale_plan_exe.spe_createTime
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    public Date getSpeCreatetime() {
        return speCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_plan_exe.spe_createTime
     *
     * @param speCreatetime the value for sale_plan_exe.spe_createTime
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    public void setSpeCreatetime(Date speCreatetime) {
        this.speCreatetime = speCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_plan_exe.spe_pId
     *
     * @return the value of sale_plan_exe.spe_pId
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    public Integer getSpePid() {
        return spePid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_plan_exe.spe_pId
     *
     * @param spePid the value for sale_plan_exe.spe_pId
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    public void setSpePid(Integer spePid) {
        this.spePid = spePid;
    }
}