package com.luckylas.crm.entity;

/**
 * 用户实体类
 * @author luckyliuqs
 *
 */
public class User {
    /**
     * 用户id
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_id
     *
     * @mbg.generated Mon Sep 30 11:43:54 CST 2019
     */
    private Integer uId;

    /**
     * 用户账户
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_account
     *
     * @mbg.generated Mon Sep 30 11:43:54 CST 2019
     */
    private String uAccount;

    /**
     * 用户名称
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_name
     *
     * @mbg.generated Mon Sep 30 11:43:54 CST 2019
     */
    private String uName;

    /**
     * 账户密码
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_password
     *
     * @mbg.generated Mon Sep 30 11:43:54 CST 2019
     */
    private String uPassword;

    /**
     * 用户头像
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_photo
     *
     * @mbg.generated Mon Sep 30 11:43:54 CST 2019
     */
    private String uPhoto;

    /**
     * 用户角色id
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_roleId
     *
     * @mbg.generated Mon Sep 30 11:43:54 CST 2019
     */
    private Integer uRoleid;
    
    /**
     * 是否记住密码
     */
    private Integer remember;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_id
     *
     * @return the value of user.u_id
     *
     * @mbg.generated Mon Sep 30 11:43:54 CST 2019
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_id
     *
     * @param uId the value for user.u_id
     *
     * @mbg.generated Mon Sep 30 11:43:54 CST 2019
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_account
     *
     * @return the value of user.u_account
     *
     * @mbg.generated Mon Sep 30 11:43:54 CST 2019
     */
    public String getuAccount() {
        return uAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_account
     *
     * @param uAccount the value for user.u_account
     *
     * @mbg.generated Mon Sep 30 11:43:54 CST 2019
     */
    public void setuAccount(String uAccount) {
        this.uAccount = uAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_name
     *
     * @return the value of user.u_name
     *
     * @mbg.generated Mon Sep 30 11:43:54 CST 2019
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_name
     *
     * @param uName the value for user.u_name
     *
     * @mbg.generated Mon Sep 30 11:43:54 CST 2019
     */
    public void setuName(String uName) {
        this.uName = uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_password
     *
     * @return the value of user.u_password
     *
     * @mbg.generated Mon Sep 30 11:43:54 CST 2019
     */
    public String getuPassword() {
        return uPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_password
     *
     * @param uPassword the value for user.u_password
     *
     * @mbg.generated Mon Sep 30 11:43:54 CST 2019
     */
    public void setuPassword(String uPassword) {
        this.uPassword = uPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_photo
     *
     * @return the value of user.u_photo
     *
     * @mbg.generated Mon Sep 30 11:43:54 CST 2019
     */
    public String getuPhoto() {
        return uPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_photo
     *
     * @param uPhoto the value for user.u_photo
     *
     * @mbg.generated Mon Sep 30 11:43:54 CST 2019
     */
    public void setuPhoto(String uPhoto) {
        this.uPhoto = uPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_roleId
     *
     * @return the value of user.u_roleId
     *
     * @mbg.generated Mon Sep 30 11:43:54 CST 2019
     */
    public Integer getuRoleid() {
        return uRoleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_roleId
     *
     * @param uRoleid the value for user.u_roleId
     *
     * @mbg.generated Mon Sep 30 11:43:54 CST 2019
     */
    public void setuRoleid(Integer uRoleid) {
        this.uRoleid = uRoleid;
    }

	public Integer getRemember() {
		return remember;
	}

	public void setRemember(Integer remember) {
		this.remember = remember;
	}
}