package com.luckylas.crm.mapper;

import com.luckylas.crm.entity.SalePlanExe;
import com.luckylas.crm.entity.SalePlanExeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SalePlanExeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan_exe
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    long countByExample(SalePlanExeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan_exe
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    int deleteByExample(SalePlanExeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan_exe
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    int deleteByPrimaryKey(Integer speId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan_exe
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    int insert(SalePlanExe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan_exe
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    int insertSelective(SalePlanExe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan_exe
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    List<SalePlanExe> selectByExample(SalePlanExeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan_exe
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    SalePlanExe selectByPrimaryKey(Integer speId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan_exe
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") SalePlanExe record, @Param("example") SalePlanExeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan_exe
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    int updateByExample(@Param("record") SalePlanExe record, @Param("example") SalePlanExeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan_exe
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    int updateByPrimaryKeySelective(SalePlanExe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_plan_exe
     *
     * @mbg.generated Mon Sep 30 11:43:00 CST 2019
     */
    int updateByPrimaryKey(SalePlanExe record);
}