package com.luckylas.crm.mapper;

import com.luckylas.crm.entity.SaleChance;
import com.luckylas.crm.entity.SaleChanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SaleChanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    long countByExample(SaleChanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    int deleteByExample(SaleChanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    int deleteByPrimaryKey(Integer scId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    int insert(SaleChance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    int insertSelective(SaleChance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    List<SaleChance> selectByExample(SaleChanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    SaleChance selectByPrimaryKey(Integer scId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    int updateByExampleSelective(@Param("record") SaleChance record, @Param("example") SaleChanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    int updateByExample(@Param("record") SaleChance record, @Param("example") SaleChanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    int updateByPrimaryKeySelective(SaleChance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_chance
     *
     * @mbg.generated Mon Sep 30 13:48:58 CST 2019
     */
    int updateByPrimaryKey(SaleChance record);
}